import { Game, Banner } from './types'

export function calcDiscount(original: number, sale: number): number {
  return Math.round(((original - sale) / original) * 100)
}

export const SEED_GAMES: Game[] = [
  {
    id: '1',
    title: 'God of War Ragnarök',
    slug: 'god-of-war-ragnarok',
    platform: 'Steam',
    originalPrice: 199.00,
    salePrice: 20.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=God+of+War',
    categories: ['Acción', 'Aventura'],
    isHot: false,
    hasDenuvo: false,
    isFeatured: true,
    isNew: false,
    accountType: 'offline',
    description: 'Kratos y Atreus deben viajar por los nueve reinos para prepararse para la profetizada batalla al final de todo.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Black Myth: Wukong',
    slug: 'black-myth-wukong',
    platform: 'Steam',
    originalPrice: 199.00,
    salePrice: 25.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=Black+Myth',
    categories: ['Acción', 'Souls'],
    isHot: true,
    hasDenuvo: true,
    isFeatured: true,
    isNew: false,
    accountType: 'offline',
    description: 'Un juego de acción en solitario ambientado en una china mitológica.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Resident Evil 4 Remake',
    slug: 'resident-evil-4-remake',
    platform: 'Steam',
    originalPrice: 109.00,
    salePrice: 24.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=RE4+Remake',
    categories: ['Acción', 'Survival Horror', 'Terror'],
    isHot: true,
    hasDenuvo: false,
    isFeatured: true,
    isNew: false,
    accountType: 'offline',
    description: 'Reconstruido desde cero para recrear el inframundo de pesadilla de la España rural.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Clair Obscur: Expedition 33',
    slug: 'clair-obscur-expedition-33',
    platform: 'Steam',
    originalPrice: 130.00,
    salePrice: 20.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=Clair+Obscur',
    categories: ['RPG', 'Aventura'],
    isHot: false,
    hasDenuvo: false,
    isFeatured: true,
    isNew: false,
    accountType: 'offline',
    description: 'Un RPG de acción galardonado con una narrativa profunda y un mundo fascinante.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Mortal Kombat 1 - Definitive Edition',
    slug: 'mortal-kombat-1-definitive',
    platform: 'Steam',
    originalPrice: 219.00,
    salePrice: 32.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=MK1',
    categories: ['Lucha', 'Acción'],
    isHot: true,
    hasDenuvo: true,
    isFeatured: true,
    isNew: false,
    accountType: 'offline',
    description: 'El reboot definitivo del universo Mortal Kombat con gráficos de última generación.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Dragon Ball: Sparking! Zero',
    slug: 'dragon-ball-sparking-zero',
    platform: 'Steam',
    originalPrice: 270.00,
    salePrice: 20.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=DB+Sparking',
    categories: ['Lucha', 'Acción'],
    isHot: false,
    hasDenuvo: false,
    isFeatured: true,
    isNew: false,
    accountType: 'offline',
    description: 'La evolución espiritual de Budokai Tenkaichi con el mayor roster de Dragon Ball.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Grand Theft Auto V: Enhanced',
    slug: 'gta-v-enhanced',
    platform: 'Steam',
    originalPrice: 110.90,
    salePrice: 24.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=GTA+V',
    categories: ['Acción', 'Mundo Abierto'],
    isHot: false,
    hasDenuvo: false,
    isFeatured: true,
    isNew: false,
    accountType: 'offline',
    description: 'La edición mejorada de uno de los juegos más vendidos de todos los tiempos.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Stellar Blade',
    slug: 'stellar-blade',
    platform: 'Steam',
    originalPrice: 199.00,
    salePrice: 27.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=Stellar+Blade',
    categories: ['Acción', 'Hack and Slash'],
    isHot: false,
    hasDenuvo: true,
    isFeatured: true,
    isNew: false,
    accountType: 'offline',
    description: 'Un juego de acción con combates espectaculares ambientado en un futuro distópico.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '9',
    title: 'Crimson Desert',
    slug: 'crimson-desert',
    platform: 'Steam',
    originalPrice: 285.00,
    salePrice: 23.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=Crimson+Desert',
    categories: ['Acción', 'RPG', 'Mundo Abierto'],
    isHot: false,
    hasDenuvo: true,
    isFeatured: true,
    isNew: false,
    accountType: 'offline',
    description: 'Un RPG de mundo abierto con combates épicos y un vasto mundo por explorar.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '10',
    title: 'Resident Evil Requiem Deluxe Edition',
    slug: 'resident-evil-requiem',
    platform: 'Steam',
    originalPrice: 219.00,
    salePrice: 29.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=RE+Requiem',
    categories: ['Survival Horror', 'Terror', 'Acción'],
    isHot: true,
    hasDenuvo: true,
    isFeatured: true,
    isNew: false,
    accountType: 'offline',
    description: 'La entrega más aterradora de Resident Evil con gráficos fotorrealistas.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '11',
    title: 'Hollow Knight: Silksong',
    slug: 'hollow-knight-silksong',
    platform: 'Steam',
    originalPrice: 43.00,
    salePrice: 15.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=Silksong',
    horizontalImage: 'https://placehold.co/460x215/1a1a2e/f97316?text=Hollow+Knight',
    categories: ['Indie', 'Metroidvania', 'Plataformas'],
    isHot: false,
    hasDenuvo: false,
    isFeatured: false,
    isNew: true,
    accountType: 'offline',
    description: 'La secuela muy esperada del aclamado Hollow Knight con la protagonista Hornet.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '12',
    title: 'Blasphemous 2',
    slug: 'blasphemous-2',
    platform: 'Steam',
    originalPrice: 74.95,
    salePrice: 15.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=Blasphemous+2',
    horizontalImage: 'https://placehold.co/460x215/1a1a2e/f97316?text=Blasphemous+2',
    categories: ['Indie', 'Metroidvania', 'Plataformas'],
    isHot: false,
    hasDenuvo: false,
    isFeatured: false,
    isNew: true,
    accountType: 'offline',
    description: 'El Penitente regresa con nuevas habilidades en este oscuro Metroidvania.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '13',
    title: 'Kena: Bridge of Spirits',
    slug: 'kena-bridge-of-spirits',
    platform: 'Steam',
    originalPrice: 120.00,
    salePrice: 20.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=Kena',
    horizontalImage: 'https://placehold.co/460x215/1a1a2e/f97316?text=Kena',
    categories: ['Indie', 'Aventura', 'Acción'],
    isHot: false,
    hasDenuvo: false,
    isFeatured: false,
    isNew: true,
    accountType: 'offline',
    description: 'Una joven guía de espíritus descubre una historia oscura mientras limpia la corrupción de la tierra.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '14',
    title: 'Pragmata',
    slug: 'pragmata',
    platform: 'Steam',
    originalPrice: 197.00,
    salePrice: 28.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=Pragmata',
    categories: ['Acción', 'Aventura', 'Shooter'],
    isHot: true,
    hasDenuvo: true,
    isFeatured: true,
    isNew: false,
    accountType: 'offline',
    description: 'Una aventura de acción ambientada en una luna distópica.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '15',
    title: '007 First Light',
    slug: '007-first-light',
    platform: 'Steam',
    originalPrice: 135.00,
    salePrice: 29.00,
    coverImage: 'https://placehold.co/280x390/1a1a2e/f97316?text=007+First+Light',
    categories: ['Acción', 'Shooter', 'Aventura'],
    isHot: true,
    hasDenuvo: false,
    isFeatured: true,
    isNew: true,
    accountType: 'offline',
    description: 'La nueva aventura de James Bond con un emocionante debut como agente 007.',
    badge: 'ESTRENO',
    createdAt: new Date().toISOString(),
  },
]

export const SEED_BANNERS: Banner[] = [
  {
    id: '1',
    title: '007',
    subtitle: 'FIRST LIGHT',
    image: 'https://placehold.co/1200x500/0b0b16/f97316?text=007+FIRST+LIGHT',
    badge: 'ESTRENO',
    date: '27/05/26',
    originalPrice: 135.00,
    salePrice: 29.00,
    discount: 78,
    ctaText: 'COMPRAR AHORA',
    active: true,
    order: 1,
  },
  {
    id: '2',
    title: 'BLACK MYTH',
    subtitle: 'WUKONG',
    image: 'https://placehold.co/1200x500/0b0b16/fbbf24?text=BLACK+MYTH+WUKONG',
    badge: 'HOT',
    date: '',
    originalPrice: 199.00,
    salePrice: 25.00,
    discount: 87,
    ctaText: 'COMPRAR AHORA',
    active: true,
    order: 2,
  },
  {
    id: '3',
    title: 'GOD OF WAR',
    subtitle: 'RAGNARÖK',
    image: 'https://placehold.co/1200x500/0b0b16/22c55e?text=GOD+OF+WAR+RAGNAROK',
    badge: '',
    date: '',
    originalPrice: 199.00,
    salePrice: 20.00,
    discount: 90,
    ctaText: 'COMPRAR AHORA',
    active: true,
    order: 3,
  },
]
